import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/Theme-Provider"
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "BRENO Tech",
  description: "Generated by Breno Rodrigues",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
        <Footer />
      </html>
    </>
  )
}
